from termcolor import colored
file=open("logo.txt","r")
print(colored(file.read(),color="red"))
name=input(colored("Your Fucking Nickname   >",color="blue"))
vulname=input(colored(" Vulnerable name   >",color="blue"))
tdomain=input(colored("Target Domain 	>",color="blue"))
vurl=input(colored("Vulnerability Url   >",color="blue"))
vpayload=input(colored("Payloads   >",color="blue"))
risk=input(colored("Risk on system   >",color="blue"))
pocst1=input(colored("poc step1(put blank if you dont need step) :",color="white"))
pocst2=input(colored("poc step2(put blank if you dont need step) :",color="white"))
pocst3=input(colored("poc step3(put blank if you dont need step) :",color="white"))
pocst4=input(colored("poc step4(put blank if you dont need step) :",color="white"))
pocst5=input(colored("poc step5(put blank if you dont need step) :",color="white"))
print(colored("                         --------------------",color="blue"))
print(colored("                         |Your Report Result|",color="red"))
print(colored("                         --------------------",color="blue"))
print("|                    Hello, admin and security team")
print("|                    My name is ",name,", i am white hat hacker from myanmar.")
print("|                    +")
print("|                    I want to report you a bug or vulnerability from your domain: ",tdomain,)
print("|                    Vulnerability name: ",vulname,)
print("|                    The vulnerable URL :",vurl)
print("|                    XSS payload is:",vpayload)
print("|                    +")
print("|                                POC steps below:")
print("|                    step1- ",pocst1," .")
print("|                    step2- ",pocst2," .")
print("|                    step3- ",pocst3," .")
print("|                    step4- ",pocst4," .")
print("|                    step5- ",pocst5," .")
print("|                    +")
print("|                    I hope you will fix it soon...........")

