from termcolor import colored
file=open("logo.txt","r")
print(colored(file.read(),color="red"))
file1=open("choose.txt","r")
print(colored(file1.read(),color="white"))
samp1=int(input(colored("Choose your sample report [1] [2] [3]   >",color="blue")))
if (samp1==1):
 print(colored("                                ________________________1_____________________",color="blue"))
 print(colored("                                |WRITE DOWN YOUR INFORMATION AND ABOUT TARGET|",color="green"))
 print(colored("                                ------------------------1---------------------",color="blue"))
 name=input(colored("Your Fucking Nickname   >",color="blue"))
 countr=input(colored("Your Fucking Country   >",color="blue"))
 vulname=input(colored(" Vulnerable name   >",color="blue"))
 tdomain=input(colored("Target Domain 	>",color="blue"))
 vurl=input(colored("Vulnerability Url   >",color="blue"))
 vpayload=input(colored("Payloads   >",color="blue"))
 risk=input(colored("Risk on system   >",color="blue"))
 pocst1=input(colored("poc step1 [put blank if you dont need step] :",color="white"))
 pocst2=input(colored("poc step2 [put blank if you dont need step] :",color="white"))
 pocst3=input(colored("poc step3 [put blank if you dont need step] :",color="white"))
 pocst4=input(colored("poc step4 [put blank if you dont need step] :",color="white"))
 pocst5=input(colored("poc step5 [put blank if you dont need step] :",color="white"))
 print(colored("                         --------------------",color="blue"))
 print(colored("                         |Your Report Result|",color="red"))
 print(colored("                         --------------------",color="blue"))
 print("|                    Hello, admin and security team")
 print("|                    My name is ",name,", i am white hat hacker from",countr,".")
 print("|                    +")
 print("|                    I want to report you a bug or vulnerability from your domain: ",tdomain,)
 print("|                    Vulnerability name: ",vulname,)
 print("|                    The vulnerable URL :",vurl)
 print("|                    XSS payload is:",vpayload)
 print("|                    +")
 print("|                                POC steps below:")
 print("|                    step1- ",pocst1,".")
 print("|                    step2- ",pocst2,".")
 print("|                    step3- ",pocst3,".")
 print("|                    step4- ",pocst4,".")
 print("|                    step5- ",pocst5,".")
 print("|                    +")
 print("|                    Impact : ",risk)
 print("|                    I hope you will fix it soon...........") 
elif (samp1==2):
 print(colored("                                ________________________2_____________________",color="blue"))
 print(colored("                                |WRITE DOWN YOUR INFORMATION AND ABOUT TARGET|",color="green"))
 print(colored("                                ------------------------2---------------------",color="blue"))
 name=input(colored("Your Fucking Nickname   >",color="blue"))
 countr=input(colored("Your Fucking Country   >",color="blue"))
 vulname=input(colored(" Vulnerable name   >",color="blue"))
 tdomain=input(colored("Target Domain 	>",color="blue"))
 vurl=input(colored("Vulnerability Url   >",color="blue"))
 vpara=input(colored("Vulnerability Parameter  >",color="blue"))
 vpayload=input(colored("Payloads   >",color="blue"))
 risk=input(colored("Risk on system   >",color="blue"))
 pocst1=input(colored("poc step1 [put blank if you dont need step] :",color="white"))
 pocst2=input(colored("poc step2 [put blank if you dont need step] :",color="white"))
 pocst3=input(colored("poc step3 [put blank if you dont need step] :",color="white"))
 pocst4=input(colored("poc step4 [put blank if you dont need step] :",color="white"))
 pocst5=input(colored("poc step5 [put blank if you dont need step] :",color="white"))
 pocst6=input(colored("poc step6 [put blank if you dont need step] :",color="white"))
 pocst7=input(colored("poc step7 [put blank if you dont need step] :",color="white"))
 print(colored("                         --------------------",color="blue"))
 print(colored("                         |Your Report Result|",color="red"))
 print(colored("                         --------------------",color="blue"))
 print("-                    Hello upserve security team,")
 print("-                    My name is ",name,", i am white hat hacker from ",countr,".")
 print("-                    +")
 print("-                    I want to report you a bug or vulnerability from your domain.")
 print("-                    I found a ",vulname,"bug or vulnerability on ",tdomain)
 print("-                    URL :",vurl)
 print("-                    Vulnerability Parameter :",vpara)
 print("-                    Payload:",vpayload)
 print("-                    +")
 print("-                                Steps to reproduce:")
 print("-                    step1- ",pocst1,".")
 print("-                    step2- ",pocst2,".")
 print("-                    step3- ",pocst3,".")
 print("-                    step4- ",pocst4,".")
 print("-                    step5- ",pocst5,".")
 print("-                    step6- ",pocst6,".")
 print("-                    step7- ",pocst7,".")
 print("-                    Risk on system : ",risk)
 print("-                    +")
 print("-                    Thanks and i hope you will fix it soon......") 
elif (samp1==3):
 print(colored("                                ________________________2_____________________",color="blue"))
 print(colored("                                |WRITE DOWN YOUR INFORMATION AND ABOUT TARGET|",color="green"))
 print(colored("                                ------------------------2---------------------",color="blue"))
 vulname=input(colored(" Vulnerable name   >",color="blue"))
 tdomain=input(colored("Target Domain   >",color="blue"))
 vurl=input(colored("Vulnerability Url   >",color="blue"))
 vpara=input(colored("Vulnerability Parameter  >",color="blue"))
 vpayload1=input(colored("Payload1   >",color="blue"))
 vpayload2=input(colored("Payload2   >",color="blue"))
 vpayload3=input(colored("Payload3   >",color="blue"))
 vpayload4=input(colored("Payload4   >",color="blue"))
 vpayload5=input(colored("Payload5   >",color="blue"))
 risk=input(colored("Write down impact   >",color="blue"))
 pocst1=input(colored("poc step1 [put blank if you dont need step] :",color="white"))
 pocst2=input(colored("poc step2 [put blank if you dont need step] :",color="white"))
 pocst3=input(colored("poc step3 [put blank if you dont need step] :",color="white"))
 pocst4=input(colored("poc step4 [put blank if you dont need step] :",color="white"))
 pocst5=input(colored("poc step5 [put blank if you dont need step] :",color="white"))
 print(colored("                         --------------------",color="blue"))
 print(colored("                         |Your Report Result|",color="red"))
 print(colored("                         --------------------",color="blue"))
 print("-                   Hello admin team and security team...")                    
 print("-                   I want to report you vulnerability ",vulname,"on domain ",tdomain)
 print("-                   +")
 print("-                   Vulnerability URL:",vurl)
 print("-                   +")
 print("-                   Vulnerability Parameter:",vpara)
 print("-                   +")
 print("-                   Available Payloads:")
 print("-                        payload 1 :",vpayload1)
 print("-                        payload 2 :",vpayload2)
 print("-                        payload 3 :",vpayload3)
 print("-                        payload 4 :",vpayload4)
 print("-                        payload 5 :",vpayload5)
 print("-                   Steps To Reproduce:")
 print("-                        step1 -",pocst1)
 print("-                        step2 -",pocst2)
 print("-                        step3 -",pocst3)
 print("-                        step4 -",pocst4)
 print("-                        step5 -",pocst5)
 print("-                    Impact : ",risk)
 print("-                   +")
 print("-                   Thanks and i hope you will fix it soon.....")
else:
 print("error command!!!")
